# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(252827)
$foreground = rgb(E8E5C8)
$color0 = rgb(4A4E4C)
$color1 = rgb(1C271E)
$color2 = rgb(494E2F)
$color3 = rgb(545B31)
$color4 = rgb(5C7478)
$color5 = rgb(767441)
$color6 = rgb(8D8849)
$color7 = rgb(D5D2A8)
$color8 = rgb(959376)
$color9 = rgb(253428)
$color10 = rgb(61673F)
$color11 = rgb(707941)
$color12 = rgb(7B9AA0)
$color13 = rgb(9E9B56)
$color14 = rgb(BCB562)
$color15 = rgb(D5D2A8)
